version: "3"
services:
  jupyter:
    image: jupyter/scipy-notebook
    ports: 
      - 8888:8888
  superset:
    image: tylerfowler/superset
    ports:
      - 8088:8088
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - SHARED_PASSWORD=pwd1234
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - .scripts/:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: